apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-completed-dagster-runs
  namespace: thanathorn55551-dev
spec:
  schedule: "0 * * * *" 
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default # ถ้า Permission Denied อาจจะต้องสร้าง SA ใหม่ที่มีสิทธิ์ลบ
          containers:
          - name: oc-container
            # เปลี่ยนมาใช้ Image ของ OpenShift CLI โดยตรง
            image: quay.io/openshift/origin-cli:latest 
            command:
            - /bin/sh
            - -c
            # ใช้คำสั่ง oc แทน kubectl
            - "oc delete pod --field-selector=status.phase=Succeeded -l dagster/job -n thanathorn55551-dev"
          restartPolicy: OnFailure