generatePostgresqlPasswordSecret: false
global:
  imagePullSecrets:
    - name: ghcr-auth
  postgresqlSecretName: "db-dagster"
  dagsterHome: "/opt/dagster/dagster_home"
  envSecrets:
    - name: db-dagster
dagsterWebserver:
  replicaCount: 1
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10" 
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080 
    annotations: {}
  readinessProbe:
      httpGet:
        path: "/server_info"
        port: 8080    # 👈 เปลี่ยนจาก 80 เป็น 8080 ให้ตรงกับแอป
      periodSeconds: 20
  livenessProbe:
    httpGet:
      path: "/server_info"
      port: 8080    # 👈 เปลี่ยนตรงนี้ด้วย
    initialDelaySeconds: 60
    periodSeconds: 20
  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local" 
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef: 
          name: "db-dagster"
          key: "postgresql-password"
    - name: AWS_ACCESS_KEY_ID
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_ACCESS_KEY_API"
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_SECRET_KEY_API"
    - name: LINE_CHANNEL_ACCESS
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_CHANNEL_ACCESS"
    - name: LINE_ADMIN_USER
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_ADMIN_USER"
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"

dagsterDaemon:
  enabled: true
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10"
    pullPolicy: Always
  envSecrets:
    - name: "db-dagster"

  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local"
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: AWS_ACCESS_KEY_ID
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_ACCESS_KEY"
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_SECRET_KEY"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "db-dagster"
          key: "postgresql-password"
    - name: LINE_CHANNEL_ACCESS
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_CHANNEL_ACCESS"
    - name: LINE_ADMIN_USER
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_ADMIN_USER"
    - name: CLIENT_ID
      valueFrom: 
        secretKeyRef:
          name: "health-secret"
          key: "CLIENT_ID"
    - name: CLIENT_SECRET
      valueFrom: 
        secretKeyRef:
          name: "health-secret"
          key: "CLIENT_SECRET"
    - name: REFRESH_TOKEN
      valueFrom: 
        secretKeyRef:
          name: "health-secret"
          key: "REFRESH_TOKEN"
    - name: GEMINI_API_KEY
      valueFrom: 
        secretKeyRef:
          name: "health-secret"
          key: "GEMINI_API_KEY"
    - name: BACKEND_API_URL
      valueFrom: 
        secretKeyRef:
          name: "health-secret"
          key: "BACKEND_API_URL"
  securityContext: {}
  
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"
  

dagster-user-deployments:
  enabled: true
  deployments:
    # -------------------------------------------------------------
    # 1. Pipeline หลัก (repo.py)
    # -------------------------------------------------------------
    - name: "my-data-pipeline"
      image:
        repository: "ghcr.io/choppertnt/dagster-assets" 
        tag: "latest"
        pullPolicy: Always
      imagePullSecrets:
        - name: ghcr-auth
      dagsterApiGrpcArgs:
        - "--python-file"
        - "repo.py"
      port: 3030
      readinessProbe:
        exec:
          command: ["dagster", "api", "grpc-health-check", "-p", "3030"]
        initialDelaySeconds: 20
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 5
      env:
        - name: HOME
          value: "/opt/dagster/dagster_home"
        - name: DB_HOST
          value: "84.247.145.103"
        - name: DB_PORT
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "DB_PORT"
        - name: DB_USER
          value: "dagster_user"
        - name: DB_NAME
          value: "postgres"
        - name: AWS_ENDPOINT_URL 
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_ACCESS_KEY"
        - name: DB_PASS 
          valueFrom:
            secretKeyRef:
              name: "db-dagster"
              key: "postgresql-password"
        - name: MINIO_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_SECRET_KEY"
        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_ACCESS_KEY"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_SECRET_KEY"
        - name: LINE_CHANNEL_ACCESS
          valueFrom: 
            secretKeyRef: 
              name: "db-dagster"
              key: "LINE_CHANNEL_ACCESS"
        - name: LINE_ADMIN_USER
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "LINE_ADMIN_USER"
        - name: CLIENT_ID
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "CLIENT_ID"
        - name: CLIENT_SECRET
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "CLIENT_SECRET"
        - name: REFRESH_TOKEN
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "REFRESH_TOKEN"
        - name: GEMINI_API_KEY
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "GEMINI_API_KEY"
        - name: BACKEND_API_URL
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "BACKEND_API_URL"

    # -------------------------------------------------------------
    # 2. Pipeline ด้าน Health (repo_health.py)
    # -------------------------------------------------------------
    - name: "health-pipeline"
      image:
        repository: "ghcr.io/choppertnt/dagster-assets" 
        tag: "latest"
        pullPolicy: Always
      imagePullSecrets:
        - name: ghcr-auth
      dagsterApiGrpcArgs:
        - "--python-file"
        - "repo_health.py"
      port: 3030
      readinessProbe:
        exec:
          command: ["dagster", "api", "grpc-health-check", "-p", "3030"]
        initialDelaySeconds: 20
        periodSeconds: 15
        timeoutSeconds: 10
        failureThreshold: 5
      env:
        - name: HOME
          value: "/opt/dagster/dagster_home"
        - name: DB_HOST
          value: "84.247.145.103"
        - name: DB_PORT
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "DB_PORT"
        - name: DB_USER
          value: "dagster_user"
        - name: DB_NAME
          value: "postgres"
        - name: AWS_ENDPOINT_URL 
          value: "http://minio.minio.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_ACCESS_KEY"
        - name: DB_PASS 
          valueFrom:
            secretKeyRef:
              name: "db-dagster"
              key: "postgresql-password"
        - name: MINIO_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_SECRET_KEY"
        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_ACCESS_KEY"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_SECRET_KEY"
        - name: LINE_CHANNEL_ACCESS
          valueFrom: 
            secretKeyRef: 
              name: "db-dagster"
              key: "LINE_CHANNEL_ACCESS"
        - name: LINE_ADMIN_USER
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "LINE_ADMIN_USER"
        - name: CLIENT_ID
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "CLIENT_ID"
        - name: CLIENT_SECRET
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "CLIENT_SECRET"
        - name: REFRESH_TOKEN
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "REFRESH_TOKEN"
        - name: GEMINI_API_KEY
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "GEMINI_API_KEY"
        - name: BACKEND_API_URL
          valueFrom: 
            secretKeyRef:
              name: "health-secret"
              key: "BACKEND_API_URL"
runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      imagePullPolicy: "Always"
      envSecrets:
        - name: db-dagster
        - name: health-secret
      runK8sConfig:
        jobSpecConfig:
          ttlSecondsAfterFinished: 600
      envVars:
        - "AWS_ENDPOINT_URL=http://minio.minio.svc.cluster.local:9000"
computeLogManager:
  type: S3ComputeLogManager
  config:
    s3ComputeLogManager:
      bucket: "dagster-logs" 
      prefix: "dagster" # แนะนำให้ใส่ prefix เพื่อให้ log เป็นระเบียบ
      endpoint_url: "http://minio.minio.svc.cluster.local:9000" 
      # 🚨 ทริคสำคัญสำหรับ MinIO: ต้องบังคับให้ใช้ path-style
      use_ssl: false # ถ้า MinIO ในคลัสเตอร์ไม่ได้ใช้ HTTPS ให้ใส่เป็น false
      kwargs:
        endpoint_url: "http://minio.minio.svc.cluster.local:9000"

postgresql:
  enabled: false 
  postgresqlHost: "internal-postgres-postgresql.postgresql.svc.cluster.local"
  postgresqlUsername: "dagster_user" 
  postgresqlDatabase: "dagster_metadata"
  postgresqlPort: 5432