generatePostgresqlPasswordSecret: false
global:
  imagePullSecrets:
    - name: ghcr-auth
  postgresqlSecretName: "db-dagster"
  dagsterHome: "/opt/dagster/dagster_home"
dagsterWebserver:
  replicaCount: 1
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10" 
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080 
    annotations: {}
  readinessProbe:
      httpGet:
        path: "/server_info"
        port: 8080    # 👈 เปลี่ยนจาก 80 เป็น 8080 ให้ตรงกับแอป
      periodSeconds: 20
  livenessProbe:
    httpGet:
      path: "/server_info"
      port: 8080    # 👈 เปลี่ยนตรงนี้ด้วย
    initialDelaySeconds: 60
    periodSeconds: 20
  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local" 
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef: 
          name: "db-dagster"
          key: "postgresql-password"
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"

dagsterDaemon:
  enabled: true
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10"
    pullPolicy: Always

  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local"
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "db-dagster"
          key: "postgresql-password"
  securityContext: {}
  
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"

dagster-user-deployments:
  enabled: true
  deployments:
    - name: "my-data-pipeline"
      image:
        repository: "ghcr.io/choppertnt/dagster-assets" 
        tag: "latest"
        pullPolicy: Always
      
      imagePullSecrets:
        - name: ghcr-auth

      dagsterApiGrpcArgs:
        - "--python-file"
        - "repo.py"
      port: 3030
      
      env:
        - name: HOME
          value: "/opt/dagster/dagster_home"

runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      imagePullPolicy: "Always"
      envSecrets:
        - name: db-dagster



postgresql:
  enabled: false 
  postgresqlHost: "internal-postgres-postgresql.postgresql.svc.cluster.local"
  postgresqlUsername: "dagster_user"
  postgresqlDatabase: "dagster_metadata"