generatePostgresqlPasswordSecret: false
global:
  imagePullSecrets:
    - name: ghcr-auth
  postgresqlSecretName: "db-dagster"
  dagsterHome: "/opt/dagster/dagster_home"
dagsterWebserver:
  replicaCount: 1
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10" 
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 8080 
    annotations: {}
  readinessProbe:
      httpGet:
        path: "/server_info"
        port: 8080    # 👈 เปลี่ยนจาก 80 เป็น 8080 ให้ตรงกับแอป
      periodSeconds: 20
  livenessProbe:
    httpGet:
      path: "/server_info"
      port: 8080    # 👈 เปลี่ยนตรงนี้ด้วย
    initialDelaySeconds: 60
    periodSeconds: 20
  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local" 
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef: 
          name: "db-dagster"
          key: "postgresql-password"
    - name: AWS_ACCESS_KEY_ID
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_ACCESS_KEY"
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_SECRET_KEY"
    - name: LINE_CHANNEL_ACCESS
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_CHANNEL_ACCESS"
    - name: LINE_ADMIN_USER
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_ADMIN_USER"
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"

dagsterDaemon:
  enabled: true
  image:
    repository: "dagster/dagster-k8s" 
    tag: "1.9.10"
    pullPolicy: Always
  envSecrets:
    - name: "db-dagster"

  env:
    - name: DAGSTER_PG_HOST
      value: "internal-postgres-postgresql.postgresql.svc.cluster.local"
    - name: DAGSTER_PG_USER
      value: "dagster_user"
    - name: DAGSTER_PG_DB
      value: "dagster_metadata"
    - name: AWS_ACCESS_KEY_ID
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_ACCESS_KEY"
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "MINIO_SECRET_KEY"
    - name: DAGSTER_PG_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "db-dagster"
          key: "postgresql-password"
    - name: LINE_CHANNEL_ACCESS
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_CHANNEL_ACCESS"
    - name: LINE_ADMIN_USER
      valueFrom: 
        secretKeyRef:
          name: "db-dagster"
          key: "LINE_ADMIN_USER"
  securityContext: {}
  
  volumes:
    - name: dagster-home-vol
      emptyDir: {}
  volumeMounts:
    - name: dagster-home-vol
      mountPath: "/opt/dagster/dagster_home"
  

dagster-user-deployments:
  enabled: true
  deployments:
    - name: "my-data-pipeline"
      image:
        repository: "ghcr.io/choppertnt/dagster-assets" 
        tag: "latest"
        pullPolicy: Always
      
      imagePullSecrets:
        - name: ghcr-auth

      dagsterApiGrpcArgs:
        - "--python-file"
        - "repo.py"
      port: 3030
      
      env:
        - name: HOME
          value: "/opt/dagster/dagster_home"
        - name: AWS_ACCESS_KEY_ID
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_ACCESS_KEY"
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "MINIO_SECRET_KEY"
        - name: LINE_CHANNEL_ACCESS
          valueFrom: 
            secretKeyRef: 
              name: "db-dagster"
              key: "LINE_CHANNEL_ACCESS"
        - name: LINE_ADMIN_USER
          valueFrom: 
            secretKeyRef:
              name: "db-dagster"
              key: "LINE_ADMIN_USER"
      envFrom:
        - secretRef:
            name: db-dagster
runLauncher:
  type: K8sRunLauncher
  config:
    k8sRunLauncher:
      imagePullPolicy: "Always"
      envSecrets:
        - name: db-dagster
      runK8sConfig:
        jobSpecConfig:
          ttlSecondsAfterFinished: 600
computeLogs:
  enabled: true
  type: S3ComputeLogManager
  config:
    s3ComputeLogManager:
      bucket: "dagster-logs" 
      endpoint_url: "http://minio.minio.svc.cluster.local:9000" # 👈 URL ของ MinIO ใน K3s
      region: "us-east-1" 



postgresql:
  enabled: false 
  postgresqlHost: "internal-postgres-postgresql.postgresql.svc.cluster.local"
  postgresqlUsername: "dagster_user" 
  postgresqlDatabase: "postgres"
  postgresqlPort: 30432